name: credit_card_slider
description: A credit card slider with ability to add custom cards using the CreditCard widget. Credit card slider can also be customised
version: 1.0.0+2
homepage: https://github.com/GursheeshSingh/creditcard_slider

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/

  fonts:
    - family: creditcard
      fonts:
        - asset: fonts/creditcard.ttf